export const CONSTANTS = {
  REQUEST_FORMAT: "application/json",
  RESPONSE_FORMAT: "application/json",
  MULTI_FORM: "multipart/form-data",
  REQUEST_POST: "POST",
  REQUEST_GET: "GET",
  REQUEST_PUT: "PUT",
  REQUEST_PATCH: "PATCH",
  REQUEST_DELETE: "DELETE",
  LANGUAGE_ENGLISH: "en",
  SECRET_KEY: "37ZA3D89B64C115122DF9178C8R99c1x",
  IV: "213A26DBB4A358C5",
  SIGNATURE_KEY: "QD32VdbRuMa0iI0q9q7cH6FIHGcNWGdEZOLyK669",
  CIPHER_KEY: "aes-256-cbc",
  HASHING_ALGORITHM: "sha256",
  WEBSITE_NAME: "NILP",
  X_AUTHORIZATION_TOKEN: `${process.env.NEXT_PUBLIC_X_AUTH_TOKEN}`,
  X_API_KEY: `${process.env.NEXT_PUBLIC_X_API_KEY}`,
  TOKEN: `${process.env.NEXT_PUBLIC_API_TOKEN}`,
  STATUS_SUCCESS: "success",
  STATUS_FAILED: "failed",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
};

export const APP_URL = {
  DEFAULT_APP_PATH: "/",
  DASHBOARD: "/dashboard",
  SAFETY_SI: "/si",
  SAFETY_SI_NEW: "/si/si-new",
  SAFETY_SI_SCHEDULE: "si/si-schedule",
  SAFETY_LW: "/lw",
  SAFETY_LW_NEW: "/lw/lw-new",
  SAFETY_LW_SCHEDULE: "lw/lw-schedule",
  SAFETY_SO: "/so",
  SAFETY_SO_NEW: "/so/so-new",
  INCIDENT_MANAGEMENT: "/incident-management",
  INCIDENT_DETAIL: "/incident-management/incident-details",
  SAFETY_ALERT: "/incident-management/safety-alert",
  PIR_EDIT: "/incident-management/pir-form-edit",
  LESSON_LEARNT: "/incident-management/lession-learnt",
  CONTRACTOR: "/contractor",
  CSM: "/csm",
  CSM_CFA_NEW: "/csm/contractor-field-audit-new",
  BHM: "/bhm",
  // MY_PORTFOLIO: "/im/my-portfolio",
  SAFETY_SCORE: "/safety-score",
  SAFETY_SCORE_NEW: "/safety-score/add-safety",
  SAFETY_SCORE_VIEW: "/safety-score/view-score",
  SAFETY_SCORE_COMMITTEE_SCORE_NEW: "/safety-score/committee-score",
  SAFETY_SCORE_COMMITTEE_SCORE_VIEW: "/safety-score/committee-view",
  MY_PORTFOLIO: "/my-draft",
  MY_DRAFT: "/im/my-draft",
  MY_ACTION: "/my-action",
  MY_SI: "/im/my-si",
  MY_SO: "/im/my-so",
  GLOBAL_ACTION: "/im/global-action",
  PIR: "/incident-management/pir-form",
  USER:"/si",
  CONTRACTOR_LOGIN: "/contractor-login",
  MOC_DASHBOARD: "/moc",
  CREATE_MOC: "/moc/create-moc",
  CHECKLIST_FORMS : "/moc/checklist-forms",
  UPDATE_MOC: "/moc/update-moc",
  UPDATE_CHECKLIST_FORMS: "/moc/update-checklist-forms",
  HOD_DETAIL_VIEW: "/moc/hoddetailview",
  HOD_PENDING: "/moc/hodpending",
  HOD_CHECKLIST_VIEW: "/moc/hodomview",
  ADMIN_DASHBOARD: "/admin",
  WORK_PLACE: "/admin/work-place",
  EMPLOYEE_MANAGE: "/admin/employee-manage",
  ROLE_MANAGE: "/admin/role-manage",
  REPORT_DASHBOARD: "/report-dashboard",
  REPORT_SI_SO_LW: "/report-si-so-lw",
  REPORT_IM: "/report-im",
  RECOMMENDATION_DASHBOARD: "/recommendation/dashboard",
  RECOMMENDATION: "/recommendation",
  };

export const USER_ROLES = {
  ROLE_ADMIN: "Admin",
};
